[build]
publish = "_site"
command = "npm run build-production"

[dev]
framework = "#static"
command = "npm start"

[[plugins]]
package = "@netlify/plugin-lighthouse"

# Fails build when a category is below a threshold
[plugins.inputs.thresholds]
performance = 0.9
accessibility = 0.9
best-practices = 0.9
seo = 0.9

[plugins.inputs]
output_path = "reports/lighthouse/index.html"

[functions]
directory = "netlify/functions/"

[[edge_functions]]
function = "user-preferences"
path = "/account/preferences/"

[[redirects]]
from = "/authors/:name/"
to = "/.netlify/builders/serverless"
status = 200
force = true
_generated_by_eleventy_serverless = "serverless"

[[redirects]]
from = "/follow/"
to = "/follow/follow.rss"
status = 301
force = true

[[redirects]]
from = "/speedlify/*"
to = "https://built-with-eleventy.netlify.app/speedlify/:splat"
status = 200
force = true

[[redirects]]
from = "/youtube"
to = "https://www.youtube.com/c/EleventyVideo"
status = 301
force = true

[[redirects]]
from = "/twitter"
to = "https://twitter.com/eleven_ty"
status = 301
force = true

[[redirects]]
from = "/docs/sites/"
to = "/speedlify/"
status = 301
force = true

[[redirects]]
from = "/docs/performance-leaderboard/"
to = "/speedlify/"
status = 301
force = true

[[redirects]]
from = "/docs/accessibility-leaderboard/"
to = "/speedlify/"
status = 301
force = true

[[redirects]]
from = "/leaderboard/*"
to = "/speedlify/"
status = 301
force = true

[[redirects]]
from = "/news/*"
to = "/blog/:splat"
status = 301
force = true

[[redirects]]
from = "/docs/how-to-support/"
to = "/docs/community/"
status = 301
force = true

[[redirects]]
from = "/docs/plugins/cache/"
to = "/docs/plugins/fetch/"
status = 301
force = true

[[headers]]
for = "/api/*"

  [headers.values]
  Access-Control-Allow-Origin = "*"
