[build]
	publish = "_site"
	command = "eleventy"
[[headers]]
	for = "/_site/css/fonts/*"
	[headers.values]
		cache-control = "max-age=2592000, public"

		Link = "</css/fonts/BenchNine-Bold-subset.woff2>; rel=preload; as=font; crossorigin; type=\"font/woff2\""
