[build]
publish = "_site"
command = "npm run build-production"

[functions]
directory = "netlify/functions/"

[[redirects]]
from = "/speedlify/*"
to = "https://built-with-eleventy.netlify.app/speedlify/:splat"
status = 200
force = true

[[redirects]]
from = "/api/screenshot/:url/:dimensions/"
to = "/.netlify/functions/screenshot"
status = 200
force = true

[[redirects]]
from = "/docs/sites/"
to = "/speedlify/"
status = 301
force = true

[[redirects]]
from = "/docs/performance-leaderboard/"
to = "/speedlify/"
status = 301
force = true

[[redirects]]
from = "/docs/accessibility-leaderboard/"
to = "/speedlify/"
status = 301
force = true

[[redirects]]
from = "/leaderboard/*"
to = "/speedlify/"
status = 301
force = true

[[redirects]]
from = "/authors/:name/"
to = "/.netlify/functions/serverless"
status = 200
force = true
_generated_by_eleventy_serverless = "serverless"

[[headers]]
for = "/api/*"

  [headers.values]
  Access-Control-Allow-Origin = "*"
