[build]
	publish = "_site"
	command = "npm run build-production"

[[redirects]]
	from = "/speedlify/*"
	to = "https://built-with-eleventy.netlify.app/speedlify/:splat"
	status = 200
	force = true

[[redirects]]
	from = "/api/screenshot/*"
	to = "/.netlify/functions/screenshot"
	status = 200
	force = true

[[redirects]]
	from = "/api/image/*"
	to = "/.netlify/functions/image"
	status = 200
	force = true

[[redirects]]
	from = "/docs/sites/"
	to = "/speedlify/"
	status = 301
	force = true

[[redirects]]
	from = "/docs/performance-leaderboard/"
	to = "/speedlify/"
	status = 301
	force = true

[[redirects]]
	from = "/docs/accessibility-leaderboard/"
	to = "/speedlify/"
	status = 301
	force = true

[[redirects]]
	from = "/leaderboard/*"
	to = "/speedlify/"
	status = 301
	force = true


[[headers]]
	for = "/api/*"
		[headers.values]
		Access-Control-Allow-Origin = "*"
