[build]
publish = "_site"
command = "npm run build-production"

## Permanent redirects

[[redirects]]
from = "/speedlify/*"
to = "https://built-with-eleventy.netlify.app/speedlify/:splat"
status = 200
force = true

[[redirects]]
from = "/mastodon"
to = "https://fosstodon.org/@eleventy"
status = 301
force = true

[[redirects]]
from = "/youtube"
to = "https://www.youtube.com/c/EleventyVideo"
status = 301
force = true

[[redirects]]
from = "/twitter"
to = "https://twitter.com/eleven_ty"
status = 301
force = true

## Feed redirects

[[redirects]]
from = "/follow/"
to = "/firehose/firehose.rss"
status = 301
force = true

[[redirects]]
from = "/follow/follow.rss"
to = "/firehose/firehose.rss"
status = 301
force = true

## Stuff has moved Redirects

[[redirects]]
from = "/docs/getting-started/"
to = "/docs/"
status = 301
force = true

[[redirects]]
from = "/docs/get-started/"
to = "/docs/"
status = 301
force = true

[[redirects]]
from = "/activity/"
to = "/firehose/"
status = 301
force = true

[[redirects]]
from = "/docs/sites/"
to = "/speedlify/"
status = 301
force = true

[[redirects]]
from = "/docs/performance-leaderboard/"
to = "/speedlify/"
status = 301
force = true

[[redirects]]
from = "/docs/accessibility-leaderboard/"
to = "/speedlify/"
status = 301
force = true

[[redirects]]
from = "/leaderboard/*"
to = "/speedlify/"
status = 301
force = true

[[redirects]]
from = "/news/*"
to = "/blog/:splat"
status = 301
force = true

[[redirects]]
from = "/docs/how-to-support/"
to = "/docs/community/"
status = 301
force = true

[[redirects]]
from = "/docs/plugins/cache/"
to = "/docs/plugins/fetch/"
status = 301
force = true

[[headers]]
for = "/api/*"

  [headers.values]
  Access-Control-Allow-Origin = "*"

[[headers]]
for = "/blog/feed.xml"

  [headers.values]
  Content-Type = "application/xml; charset=utf-8"
  x-content-type-options = "nosniff"

[[plugins]]
# https://github.com/netlify/netlify-plugin-lighthouse
package = "@netlify/plugin-lighthouse"

  # Fails build when a category is below a threshold
  [plugins.inputs.thresholds]
  performance = 1.0
  accessibility = 1.0
  best-practices = 1.0
  seo = 1.0

  # This broke redirects
  # [plugins.inputs]
  # output_path = "reports/lighthouse/index.html"
