[build]
	publish = "_site"
	command = "npm run build-production"

[[redirects]]
	from = "/docs/sites/"
	to = "/leaderboard/"
	status = 301
	force = true

[[redirects]]
	from = "/docs/performance-leaderboard/"
	to = "/leaderboard/perf/"
	status = 301
	force = true

[[redirects]]
	from = "/docs/accessibility-leaderboard/"
	to = "/leaderboard/a11y/"
	status = 301
	force = true
