const { builder } = require("@netlify/functions");
const { Serverless } = require("@11ty/eleventy");

// For the bundler, generated by the serverless plugin
try { require("./eleventy-bundler-modules.js"); } catch(e) {}

function getEleventyInstance(path, options) {
	return new Serverless("serverless", path, Object.assign({
		functionsDir: "netlify/functions/",
	}, options));
}

async function handler (event) {
	try {
		let inst = getEleventyInstance(event.path, {
			query: event.queryStringParameters,
			precompiledCollections: require("./serverless-collections.json")
		});

		return {
			statusCode: 200,
			headers: {
				"content-type": "text/html; charset=UTF-8"
			},
			body: await inst.render(),
			isBase64Encoded: false
		};
	} catch (error) {
		console.log("Error", error);

		return {
			statusCode: 500,
			body: JSON.stringify({
				error: error.message
			})
		};
	}
}

exports.getEleventy = getEleventyInstance;

// Netlify function
// exports.handler = handler;

// Netlify On-demand builder
exports.handler = builder(handler);
